import Nav from "@/components/Nav";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body style={{ display: "flex" }}>
    //     <Nav />
    //     <div style={{ flex: 1 }}>
    //       <div style={{ marginLeft: "5vw" }}>{children}</div>
    //     </div>
    //   </body>
    // </html>
    <html lang="en">
      <body>
        <div style={{ display: "flex" }}>
          <div style={{ width: "200px" }}>
            <Nav />
          </div>
          <div style={{ flexGrow: 1, padding: "0.75rem" }}>{children}</div>
        </div>
      </body>
    </html>
  );
}
